# 1. BUILD
FROM maven:3.9.9-amazoncorretto-21 AS build
WORKDIR /build

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B clean package -DskipTests


# 2. RUN
FROM amazoncorretto:21-alpine
COPY --from=build /build/target/measurements-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]