
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202510.26.0"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.synced_folder "/Users/luka/Desktop/docker-delavnica/primeri", "/home/vagrant/primeri",
    owner: "vagrant",
    group: "vagrant"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    # v.name = "dockervm-my-ip"
    v.memory = 2048
  end

  config.vm.provision "shell", path: "setup.sh"
  
end
